language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

branches:
  only:
    - master
    - dev
script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 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  
  local_dir: build
  keep-history: true
  on:
    branch: master
